package by.tc.photobook.controller.command;

public enum CommandName {
	LOADMAINPAGE, LOADREGPAGE, REGISTRATION, LOADAUTHPAGE, AUTHORIZATION, LOGOUT,
	LOADPROFILEPAGE, EDITPROFILE, SAVECHANGES, SAVEPHOTOCHANGES, EN, RU, ADDPHOTO,
	SAVENEWPHOTO, LOADPHOTOPAGE, NEWCOMMENT, RATEPHOTO, DELETEPHOTO, LOADUSERPAGE, 
	LOADPHOTOSHOOTPAGE
}
