package by.tc.photobook.controller.command;

public enum CommandName {
	LOADMAINPAGE, LOADREGPAGE, REGISTRATION, LOADAUTHPAGE, AUTHORIZATION, LOGOUT,LOADPROFILEPAGE, 
	SAVECHANGES, SAVEPHOTOCHANGES, EN, RU, SAVENEWPHOTO, LOADPHOTOPAGE, NEWCOMMENT, RATEPHOTO, 
	DELETEPHOTO, LOADUSERPAGE, LOADPHOTOSHOOTPAGE, ADDPHOTOSHOOT, SAVEPHOTOSHOOT, DELETEPHOTOSHOOT,
	SAVEPHOTOSHOOTEDIT, LOADPHOTOSHOOTS, ORDERPHOTOSHOOT, SAVEORDER, PROCESSORDER, LOADORDERSPAGE, CANCELORDER,
	ADDPHOTOSHOOTTYPE, LOADEMAILPAGE, SENDEMAIL, SEARCHUSER, LOADALLUSERSPAGE, BLOCKUNLOCK, DELETECOMMENT,
	NEWCOMPLAINT, LOADREPORTPAGE, LOADCOMPLAINTSPAGE, VIEWCOMPLAINT
}
