package by.tc.photobook.controller.command;


/** 
 * Emun that contains names of all the available commands in the app
 * @author Darya Minina
*/
public enum CommandName {
	LOADMAINPAGE, LOADREGPAGE, REGISTRATION, LOADAUTHPAGE, AUTHORIZATION, LOGOUT,LOADPROFILEPAGE, 
	SAVECHANGES,  EN, RU, SAVENEWPHOTO, LOADPHOTOPAGE, NEWCOMMENT, RATEPHOTO, 
	DELETEPHOTO, LOADUSERPAGE, LOADPHOTOSHOOTPAGE, ADDPHOTOSHOOT, SAVEPHOTOSHOOT, DELETEPHOTOSHOOT,
	SAVEPHOTOSHOOTEDIT, LOADPHOTOSHOOTS, ORDERPHOTOSHOOT, PROCESSORDER, LOADORDERSPAGE, CANCELORDER,
	ADDPHOTOSHOOTTYPE, LOADEMAILPAGE, SEARCHUSER, LOADALLUSERSPAGE, BLOCKUNLOCK, DELETECOMMENT,
	NEWCOMPLAINT, LOADREPORTPAGE, LOADCOMPLAINTSPAGE, VIEWCOMPLAINT
}
